services:
  si-beaver:
    build: .
    container_name: si-beaver
    restart: unless-stopped
    ports:
      - "7420:7420"
    environment:
      - SI_BEAVER_PORT=7420
      - DATABASE_URL=postgres://sibeaver:sibeaver@10.1.1.40:5432/sibeaver
